const Texts = {
  novopedido: "Adicionar ao Carrinho",
  add: "Adicionar",
  additionals: "Adicionais",
  aberto_ate: "Aberto até as",
  carrinho: "Meu Pedido",
  item: "item",
  items: "itens",
  inicio: "Início",
  subtotal: "Subtotal",
  finalizar_pagamento: "Finalizar Pedido",
  finalizando_pedido: "Finalizando Pedido...",
  resumo_valores: "Resumo de Valores",
  entrega: "Entrega",
  km: "km",
  salvar: "Salvar",
  voltar: "Voltar",
  fora_area_delivery: "Fora da área de entrega",
  total: "Total",
  fora_area: "Fora da área de entrega",
  alter: "Alterar",
  metodos_pagamentos: "Pagamento",
  todos: "Todos",
  telefone: "Telefone",
  endereco: "Endereço",
  credit: "Crédito",
  debit: "Débito",
  money: "Dinheiro",
  pix: "PIX",
  nome_es: "Nome",
  erroPedido: "Ocorreu um erro ao fazer o pedido. Tente novamente.",
  calculando: "Calculando...",
  nenhum_estabelecimento_aberto: "Nenhum restaurante aberto no momento.",

  IN_ROUTE_COLECT: "A caminho da coleta",
  AWAIT_COLECT: "Aguardando Pedido",
  AWAIT_APPROVE: "Aguardando Aprovação",
  DONE: "Em rota de entrega",
  IN_ROUTE_DELIVERY: "Em rota de entrega",
  APPROVED: "Preparando seu pedido",
  FINISH: "Entregue",
  FINISHED: "Entregue",
  forma_pay: "Pagamento",

  search_placeholder: "Buscar pratos...",
  popular: "Populares",
  categories: "Categorias",
  your_orders: "Meus Pedidos",
  repeat_order: "Repetir pedido",
  rate_order: "Avaliar",
  coupons: "Cupons de desconto",
  apply_coupon: "Aplicar cupom",
  coupon_placeholder: "Digite o código do cupom",
  discount: "Desconto",
  payment_split: "Dividir pagamento",
  payment_online: "Pagar online",
  order_history: "Histórico de Pedidos",
  delivery_fee: "Taxa de entrega",
  free_delivery: "Entrega grátis",
  estimated_time: "Tempo estimado",
  order_number: "Pedido #",
  see_all: "Ver todos",
  min: "min",
};
export default Texts;
