import i18n from "@/i18n";

const Texts = {
  get coleta() { return i18n.t("coleta"); },
  get disponivel() { return i18n.t("disponivel"); },
  get indisponivel() { return i18n.t("indisponivel"); },
  get notificacoes() { return i18n.t("notificacoes"); },
  get perfil() { return i18n.t("perfil"); },
  get maps() { return i18n.t("maps"); },
  get aceitar() { return i18n.t("aceitar"); },
  get confirmar() { return i18n.t("confirmar"); },
  get valorEntrega() { return i18n.t("valorEntrega"); },
  get establishment() { return i18n.t("establishment"); },
  get localizacao() { return i18n.t("localizacao"); },
  get cliente() { return i18n.t("cliente"); },
  get nome() { return i18n.t("nome"); },
  get distancia() { return i18n.t("distancia"); },
  get data() { return i18n.t("data"); },
  get km() { return i18n.t("km"); },
  get aceitar_entrega() { return i18n.t("aceitar_entrega"); },
  get valor() { return i18n.t("valor"); },
  get minutos() { return i18n.t("minutos"); },
  get pedido() { return i18n.t("pedido"); },
  get compartilhar() { return i18n.t("compartilhar"); },
  get aceitar_rota() { return i18n.t("aceitar_rota"); },
  get entrega() { return i18n.t("entrega"); },
  get voltar() { return i18n.t("voltar"); },
  get em_entrega() { return i18n.t("em_entrega"); },
  get continue_duvida() { return i18n.t("continue_duvida"); },
  get nao_sera_possivel_voltar() { return i18n.t("nao_sera_possivel_voltar"); },
  get notfound_extract() { return i18n.t("notfound_extract"); },
  get extract() { return i18n.t("extract"); },
  get codigo() { return i18n.t("codigo"); },
  get codigo_errado() { return i18n.t("codigo_errado"); },
  get config() { return i18n.t("config"); },
  get inicio() { return i18n.t("inicio"); },
  get extrato() { return i18n.t("extrato"); },
  get ajuda() { return i18n.t("ajuda"); },
  get IN_ROUTE_COLECT() { return i18n.t("IN_ROUTE_COLECT"); },
  get AWAIT_COLECT() { return i18n.t("AWAIT_COLECT"); },
  get IN_ROUTE_DELIVERY() { return i18n.t("IN_ROUTE_DELIVERY"); },
  get FINISH() { return i18n.t("FINISH"); },
  get FINISHED() { return i18n.t("FINISHED"); },
};

export default Texts;
